# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WKWebViewLearn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WKWebViewLearn
 pod 'WebViewJavascriptBridge'

  target 'WKWebViewLearnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WKWebViewLearnUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
